# Generated by Django 5.2.17 on 2026-09-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('CONCIERTO', 'Conciertos'), ('FESTIVAL', 'Festivales'), ('TEATRO', 'Teatro'), ('STANDUP', 'Stand-up'), ('DEPORTE', 'Deportes'), ('FAMILIAR', 'Familiar'), ('OTRO', 'Otros')], default='CONCIERTO', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
    ]
