# Generated by Django 5.2.17 on 2026-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.UniqueConstraint(fields=('carrito', 'sector'), name='unique_sector_por_carrito'),
        ),
    ]
