# Generated by Django 5.2.17 on 2026-09-30 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('utilizada', models.BooleanField(default=False)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='compras.compra')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='eventos.sector')),
            ],
        ),
    ]
